{
 "title": "EMR",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "memory_total",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Memory Used % ( All Slaves )",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(memory_used{exported_job=\"emr-blog\",type=\"slave\"})/sum(memory_total{exported_job=\"emr-blog\",type=\"slave\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk /mnt Used % ( All Slaves )",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(disk_used_size{exported_job=\"emr-blog\",type=\"slave\"})/sum(disk_size{exported_job=\"emr-blog\",type=\"slave\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "memory_free",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "CPU System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_sys_load",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "memory_used",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "CPU User Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_user_load",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "disk_size",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "CPU Idle Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_idle_load",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Disk Used Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "disk_used_size",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percentage",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  },
  {
   "title": "Disk Available Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "disk_available_size",
     "legendFormat": "{{ type }} {{ exported_instance }}"
    }
   ]
  }
 ]
}